repos:
  # Secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  # Conventional commit linting
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --types=feat,fix,chore,refactor,docs
          - --body-max-line-length=250

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^bin/
      - id: trailing-whitespace
        exclude: ^bin/
      - id: mixed-line-ending
        exclude: ^bin/

  # Shell script checks
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        files: \.(sh|bash)$
        exclude: ^bin/
        args: [--severity=warning]
      - id: shfmt
        name: shfmt
        entry: shfmt
        language: system
        types: [shell]
        files: \.(sh|bash)$
        exclude: ^bin/
        args: [-w, -i, "2"]

  # Go formatting
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        files: \.go$
        args: [-w, -s]
