# ~/.codex/config.toml
# Recommended safe defaults for Codex CLI
# NOTE: In Codex, TOML root keys must be listed before tables.

# Model defaults
model = "gpt-5-codex"
model_reasoning_effort = "high"

# Approval & sandbox policies
approval_policy = "untrusted"           # "untrusted" | "on-failure" | "on-request" | "never"
sandbox_mode = "workspace-write"        # "read-only" | "workspace-write" | "danger-full-access"

# Privacy
disable_response_storage = false        # set true only if you have ZDR enabled
network_access = true

[tools]
web_search = false                      # enable when needed

[shell_environment_policy]
inherit = "all"
experimental_use_profile = true
ignore_default_excludes = false

# --- MCP servers ---
# Add MCP servers as needed:
# [mcp_servers.example]
# command = "npx"
# args = ["-y", "@example/mcp-server"]
